version: '3.7'

services:
    app:
        build:
            context: ./django-app
            dockerfile: Dockerfile.dev
        ports:
            - "8000:8000"
        restart: on-failure
        volumes:
            - ./django-app/app/:/usr/src/app/
            - static_files:/usr/src/staticfiles/
            - media_files:/usr/src/mediafiles/
        env_file: 
            - ./.env.dev
        depends_on:
            - db
            - redis

    db:
        image: postgres:12.0-alpine
        restart: on-failure
        volumes:
            - postgres_data:/usr/src/postgresql/data/
        env_file: 
            - ./.env.dev
        ports:
            - "5433:5432"

    celery:
        build:
            context: ./django-app
            dockerfile: Dockerfile.dev
        command: celery -A app worker -l DEBUG
        volumes:
            - ./django-app/app/:/usr/src/app/
            - static_files:/usr/src/staticfiles/
            - media_files:/usr/src/mediafiles/
        env_file:
            - ./.env.dev
        depends_on:
            - db
            - app
            - redis

    celery-beat:
        build:
            context: ./django-app
            dockerfile: Dockerfile.dev
        command: celery -A app beat -l DEBUG --scheduler django_celery_beat.schedulers:DatabaseScheduler
        volumes:
            - ./django-app/app/:/usr/src/app/
            - static_files:/usr/src/staticfiles/
            - media_files:/usr/src/mediafiles/
        env_file:
            - ./.env.dev
        depends_on:
            - db
            - app
            - redis
    
    redis:
        image: redis:5-alpine

volumes:
    postgres_data:
    media_files:
    static_files: